language: c
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install -y gcc-9 g++-9
  - sudo apt-get install -y make
  - rm /usr/bin/gcc
  - rm /usr/bin/g++
  - ln -s /usr/bin/gcc-9 /usr/bin/gcc
  - ln -s /usr/bin/g++-9 /usr/bin/g++
  - export IP_ID_OFFSET=0
script: make
