language: c
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install -y gcc-9 g++-9
  - sudo update-alternatives --set gcc /usr/bin/gcc-9
  - sudo update-alternatives --set g++ /usr/bin/g++-9
  - sudo apt-get install -y make
  - export IP_ID_OFFSET=0
script: make
