language: c
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install -y gcc-8.2 g++-8.2
  - sudo update-alternatives --set gcc /usr/bin/gcc-8.2
  - sudo update-alternatives --set g++ /usr/bin/g++-8.2
  - sudo apt-get install -y make
  - export IP_ID_OFFSET=0
script: make
