language: c
before_install:
  - sudo update-alternatives --remove-all gcc 
  - sudo update-alternatives --remove-all g++
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install -y gcc-9 g++-9
  - sudo apt-get install -y make
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 20
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 20
  - sudo update-alternatives --install /usr/bin/cc cc /usr/bin/gcc 30
  - sudo update-alternatives --set cc /usr/bin/gcc
  - sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++ 30
  - sudo update-alternatives --set c++ /usr/bin/g++
  - sudo update-alternatives --config gcc
  - sudo update-alternatives --config g++
  - export IP_ID_OFFSET=0
script: make
