CC=gcc
CFLAGS=-O2 -fopenmp -pthread -Wall -Wextra -Werror -Wfatal-errors
DEFINES=-DFORCE_DIRECT_MAPPING -DOMP_NUM_THREADS=$(OMP_NUM_THREADS)
DEFINES_COMBINER=-DMP_USE_COMBINER
DEFINES_MUTEX=-DMP_USE_MUTEX
DEFINES_SPINLOCK=-DMP_USE_SPINLOCK
DEFINES_SPREAD=-DMP_USE_SPREAD
DEFINES_SINGLE_BROADCAST=-DMP_USE_SINGLE_BROADCAST
DEFINES_UNUSED_IN_NEIGHBOURS=-DMP_UNUSED_IN_NEIGHBOURS
DEFINES_UNUSED_OUT_NEIGHBOURS_VALUES=-DMP_UNUSED_OUT_NEIGHBOURS_VALUES
DEFINES_UNUSED_OUT_NEIGHBOURS=-DMP_UNUSED_OUT_NEIGHBOURS

SUFFIX_NO_COMBINER=_no_combiner
SUFFIX_COMBINER=_combiner
SUFFIX_MUTEX=_mutex
SUFFIX_SPINLOCK=_spinlock
SUFFIX_SPREAD=_spread
SUFFIX_SINGLE_BROADCAST=_single_broadcast
SUFFIX_UNUSED_IN_NEIGHBOURS=_unused_in_neighbours
SUFFIX_UNUSED_OUT_NEIGHBOURS_VALUES=_unused_out_neighbours_values
SUFFIX_UNUSED_OUT_NEIGHBOURS=_unused_out_neighbours

SRC_DIRECTORY=src
BENCHMARKS_DIRECTORY=benchmarks
BIN_DIRECTORY=bin

default: all

all: contiguouer \
	 contiguouerASCII \
	 graph_converter \
	 graph_generator \
	 mirror_checker_combiner \
	 all_hashmin \
	 all_pagerank \
	 all_sssp

contiguouer:
	g++ -o $(BIN_DIRECTORY)/contiguouer $(SRC_DIRECTORY)/contiguouer.cpp -O2 -std=c++11

contiguouerASCII:
	g++ -o $(BIN_DIRECTORY)/contiguouerASCII $(SRC_DIRECTORY)/contiguouerASCII.cpp -O2 -std=c++11

graph_converter:
	g++ -o $(BIN_DIRECTORY)/graph_converter $(SRC_DIRECTORY)/graph_converter.cpp -O2

graph_generator:
	g++ -o $(BIN_DIRECTORY)/graph_generator $(SRC_DIRECTORY)/graph_generator.cpp -O2 -std=c++11

mirror_checker_combiner:
	$(CC) -o $(BIN_DIRECTORY)/mirror_checker_combiner $(BENCHMARKS_DIRECTORY)/mirror_checker.c -I$(SRC_DIRECTORY) -std=c99 $(DEFINES) $(DEFINES_COMBINER) $(CFLAGS)

###########
# HASHMIN #
###########
all_hashmin: hashmin$(SUFFIX_NO_COMBINER) \
			 hashmin$(SUFFIX_COMBINER)$(SUFFIX_MUTEX) \
			 hashmin$(SUFFIX_COMBINER)$(SUFFIX_MUTEX)$(SUFFIX_UNUSED_IN_NEIGHBOURS) \
			 hashmin$(SUFFIX_COMBINER)$(SUFFIX_MUTEX)$(SUFFIX_SPREAD) \
			 hashmin$(SUFFIX_COMBINER)$(SUFFIX_MUTEX)$(SUFFIX_SPREAD)$(SUFFIX_UNUSED_IN_NEIGHBOURS) \
			 hashmin$(SUFFIX_COMBINER)$(SUFFIX_SPINLOCK) \
			 hashmin$(SUFFIX_COMBINER)$(SUFFIX_SPINLOCK)$(SUFFIX_UNUSED_IN_NEIGHBOURS) \
			 hashmin$(SUFFIX_COMBINER)$(SUFFIX_SPINLOCK)$(SUFFIX_SPREAD) \
			 hashmin$(SUFFIX_COMBINER)$(SUFFIX_SPINLOCK)$(SUFFIX_SPREAD)$(SUFFIX_UNUSED_IN_NEIGHBOURS) \
			 hashmin$(SUFFIX_COMBINER)$(SUFFIX_SINGLE_BROADCAST) \
			 hashmin$(SUFFIX_COMBINER)$(SUFFIX_SINGLE_BROADCAST)$(SUFFIX_SPREAD)

hashmin$(SUFFIX_NO_COMBINER):
	$(CC) -o $(BIN_DIRECTORY)/hashmin$(SUFFIX_NO_COMBINER) $(BENCHMARKS_DIRECTORY)/hashmin.c -I$(SRC_DIRECTORY) -std=c99 $(DEFINES) $(CFLAGS)

hashmin$(SUFFIX_COMBINER)$(SUFFIX_MUTEX):
	$(CC) -o $(BIN_DIRECTORY)/hashmin$(SUFFIX_COMBINER)$(SUFFIX_MUTEX) $(BENCHMARKS_DIRECTORY)/hashmin.c -I$(SRC_DIRECTORY) -std=c99 $(DEFINES) $(DEFINES_COMBINER) $(DEFINES_MUTEX) $(CFLAGS)

hashmin$(SUFFIX_COMBINER)$(SUFFIX_MUTEX)$(SUFFIX_UNUSED_IN_NEIGHBOURS):
	$(CC) -o $(BIN_DIRECTORY)/hashmin$(SUFFIX_COMBINER)$(SUFFIX_MUTEX)$(SUFFIX_UNUSED_IN_NEIGHBOURS) $(BENCHMARKS_DIRECTORY)/hashmin.c -I$(SRC_DIRECTORY) -std=c99 $(DEFINES) $(DEFINES_COMBINER) $(DEFINES_MUTEX) $(DEFINES_UNUSED_IN_NEIGHBOURS) $(CFLAGS)

hashmin$(SUFFIX_COMBINER)$(SUFFIX_MUTEX)$(SUFFIX_SPREAD):
	$(CC) -o $(BIN_DIRECTORY)/hashmin$(SUFFIX_COMBINER)$(SUFFIX_MUTEX)$(SUFFIX_SPREAD) $(BENCHMARKS_DIRECTORY)/hashmin.c -I$(SRC_DIRECTORY) -std=c99 $(DEFINES) $(DEFINES_COMBINER) $(DEFINES_MUTEX) $(DEFINES_SPREAD) $(CFLAGS)

hashmin$(SUFFIX_COMBINER)$(SUFFIX_MUTEX)$(SUFFIX_SPREAD)$(SUFFIX_UNUSED_IN_NEIGHBOURS):
	$(CC) -o $(BIN_DIRECTORY)/hashmin$(SUFFIX_COMBINER)$(SUFFIX_MUTEX)$(SUFFIX_SPREAD)$(SUFFIX_UNUSED_IN_NEIGHBOURS) $(BENCHMARKS_DIRECTORY)/hashmin.c -I$(SRC_DIRECTORY) -std=c99 $(DEFINES) $(DEFINES_COMBINER) $(DEFINES_MUTEX) $(DEFINES_SPREAD) $(DEFINES_UNUSED_IN_NEIGHBOURS) $(CFLAGS)

hashmin$(SUFFIX_COMBINER)$(SUFFIX_SPINLOCK):
	$(CC) -o $(BIN_DIRECTORY)/hashmin$(SUFFIX_COMBINER)$(SUFFIX_SPINLOCK) $(BENCHMARKS_DIRECTORY)/hashmin.c -I$(SRC_DIRECTORY) -std=gnu99 $(DEFINES) $(DEFINES_COMBINER) $(DEFINES_SPINLOCK) $(CFLAGS)

hashmin$(SUFFIX_COMBINER)$(SUFFIX_SPINLOCK)$(SUFFIX_UNUSED_IN_NEIGHBOURS):
	$(CC) -o $(BIN_DIRECTORY)/hashmin$(SUFFIX_COMBINER)$(SUFFIX_SPINLOCK)$(SUFFIX_UNUSED_IN_NEIGHBOURS) $(BENCHMARKS_DIRECTORY)/hashmin.c -I$(SRC_DIRECTORY) -std=gnu99 $(DEFINES) $(DEFINES_COMBINER) $(DEFINES_SPINLOCK) $(DEFINES_UNUSED_IN_NEIGHBOURS) $(CFLAGS)

hashmin$(SUFFIX_COMBINER)$(SUFFIX_SPINLOCK)$(SUFFIX_SPREAD):
	$(CC) -o $(BIN_DIRECTORY)/hashmin$(SUFFIX_COMBINER)$(SUFFIX_SPINLOCK)$(SUFFIX_SPREAD) $(BENCHMARKS_DIRECTORY)/hashmin.c -I$(SRC_DIRECTORY) -std=gnu99 $(DEFINES) $(DEFINES_COMBINER) $(DEFINES_SPINLOCK) $(DEFINES_SPREAD) $(CFLAGS)

hashmin$(SUFFIX_COMBINER)$(SUFFIX_SPINLOCK)$(SUFFIX_SPREAD)$(SUFFIX_UNUSED_IN_NEIGHBOURS):
	$(CC) -o $(BIN_DIRECTORY)/hashmin$(SUFFIX_COMBINER)$(SUFFIX_SPINLOCK)$(SUFFIX_SPREAD)$(SUFFIX_UNUSED_IN_NEIGHBOURS) $(BENCHMARKS_DIRECTORY)/hashmin.c -I$(SRC_DIRECTORY) -std=gnu99 $(DEFINES) $(DEFINES_COMBINER) $(DEFINES_SPINLOCK) $(DEFINES_SPREAD) $(DEFINES_UNUSED_IN_NEIGHBOURS) $(CFLAGS)

hashmin$(SUFFIX_COMBINER)$(SUFFIX_SINGLE_BROADCAST):
	$(CC) -o $(BIN_DIRECTORY)/hashmin$(SUFFIX_COMBINER)$(SUFFIX_SINGLE_BROADCAST) $(BENCHMARKS_DIRECTORY)/hashmin.c -I$(SRC_DIRECTORY) -std=c99 $(DEFINES) $(DEFINES_COMBINER) $(DEFINES_SINGLE_BROADCAST) $(CFLAGS)

hashmin$(SUFFIX_COMBINER)$(SUFFIX_SINGLE_BROADCAST)$(SUFFIX_SPREAD):
	$(CC) -o $(BIN_DIRECTORY)/hashmin$(SUFFIX_COMBINER)$(SUFFIX_SINGLE_BROADCAST)$(SUFFIX_SPREAD) $(BENCHMARKS_DIRECTORY)/hashmin.c -I$(SRC_DIRECTORY) -std=c99 $(DEFINES) $(DEFINES_COMBINER) $(DEFINES_SINGLE_BROADCAST) $(DEFINES_SPREAD) $(CFLAGS)

############
# PAGERANK #
############
all_pagerank: pagerank$(SUFFIX_NO_COMBINER) \
			  pagerank$(SUFFIX_COMBINER)$(SUFFIX_MUTEX) \
			  pagerank$(SUFFIX_COMBINER)$(SUFFIX_MUTEX)$(SUFFIX_UNUSED_IN_NEIGHBOURS) \
			  pagerank$(SUFFIX_COMBINER)$(SUFFIX_MUTEX)$(SUFFIX_UNUSED_OUT_NEIGHBOURS_VALUES) \
			  pagerank$(SUFFIX_COMBINER)$(SUFFIX_SPINLOCK) \
			  pagerank$(SUFFIX_COMBINER)$(SUFFIX_SPINLOCK)$(SUFFIX_UNUSED_IN_NEIGHBOURS) \
			  pagerank$(SUFFIX_COMBINER)$(SUFFIX_SPINLOCK)$(SUFFIX_UNUSED_OUT_NEIGHBOURS_VALUES) \
			  pagerank$(SUFFIX_COMBINER)$(SUFFIX_SINGLE_BROADCAST) \
			  pagerank$(SUFFIX_COMBINER)$(SUFFIX_SINGLE_BROADCAST)$(SUFFIX_UNUSED_OUT_NEIGHBOURS_VALUES)

pagerank$(SUFFIX_NO_COMBINER):
	$(CC) -o $(BIN_DIRECTORY)/pagerank$(SUFFIX_NO_COMBINER) $(BENCHMARKS_DIRECTORY)/pagerank.c -I$(SRC_DIRECTORY) -std=c99 $(DEFINES) $(CFLAGS)

pagerank$(SUFFIX_COMBINER)$(SUFFIX_MUTEX):
	$(CC) -o $(BIN_DIRECTORY)/pagerank$(SUFFIX_COMBINER)$(SUFFIX_MUTEX) $(BENCHMARKS_DIRECTORY)/pagerank.c -I$(SRC_DIRECTORY) -std=c99 $(DEFINES) $(DEFINES_COMBINER) $(DEFINES_MUTEX) $(CFLAGS)

pagerank$(SUFFIX_COMBINER)$(SUFFIX_MUTEX)$(SUFFIX_UNUSED_IN_NEIGHBOURS):
	$(CC) -o $(BIN_DIRECTORY)/pagerank$(SUFFIX_COMBINER)$(SUFFIX_MUTEX)$(SUFFIX_UNUSED_IN_NEIGHBOURS) $(BENCHMARKS_DIRECTORY)/pagerank.c -I$(SRC_DIRECTORY) -std=c99 $(DEFINES) $(DEFINES_COMBINER) $(DEFINES_MUTEX) $(DEFINES_UNUSED_IN_NEIGHBOURS) $(CFLAGS)

pagerank$(SUFFIX_COMBINER)$(SUFFIX_MUTEX)$(SUFFIX_UNUSED_OUT_NEIGHBOURS_VALUES):
	$(CC) -o $(BIN_DIRECTORY)/pagerank$(SUFFIX_COMBINER)$(SUFFIX_MUTEX)$(SUFFIX_UNUSED_OUT_NEIGHBOURS_VALUES) $(BENCHMARKS_DIRECTORY)/pagerank.c -I$(SRC_DIRECTORY) -std=c99 $(DEFINES) $(DEFINES_COMBINER) $(DEFINES_MUTEX) $(DEFINES_UNUSED_OUT_NEIGHBOURS_VALUES) $(CFLAGS)

pagerank$(SUFFIX_COMBINER)$(SUFFIX_SPINLOCK):
	$(CC) -o $(BIN_DIRECTORY)/pagerank$(SUFFIX_COMBINER)$(SUFFIX_SPINLOCK) $(BENCHMARKS_DIRECTORY)/pagerank.c -I$(SRC_DIRECTORY) -std=gnu99 $(DEFINES) $(DEFINES_COMBINER) $(DEFINES_SPINLOCK) $(CFLAGS)

pagerank$(SUFFIX_COMBINER)$(SUFFIX_SPINLOCK)$(SUFFIX_UNUSED_IN_NEIGHBOURS):
	$(CC) -o $(BIN_DIRECTORY)/pagerank$(SUFFIX_COMBINER)$(SUFFIX_SPINLOCK)$(SUFFIX_UNUSED_IN_NEIGHBOURS) $(BENCHMARKS_DIRECTORY)/pagerank.c -I$(SRC_DIRECTORY) -std=gnu99 $(DEFINES) $(DEFINES_COMBINER) $(DEFINES_SPINLOCK) $(DEFINES_UNUSED_IN_NEIGHBOURS) $(CFLAGS)

pagerank$(SUFFIX_COMBINER)$(SUFFIX_SPINLOCK)$(SUFFIX_UNUSED_OUT_NEIGHBOURS_VALUES):
	$(CC) -o $(BIN_DIRECTORY)/pagerank$(SUFFIX_COMBINER)$(SUFFIX_SPINLOCK)$(SUFFIX_UNUSED_OUT_NEIGHBOURS_VALUES) $(BENCHMARKS_DIRECTORY)/pagerank.c -I$(SRC_DIRECTORY) -std=gnu99 $(DEFINES) $(DEFINES_COMBINER) $(DEFINES_SPINLOCK) $(DEFINES_UNUSED_OUT_NEIGHBOURS_VALUES) $(CFLAGS)

pagerank$(SUFFIX_COMBINER)$(SUFFIX_SINGLE_BROADCAST):
	$(CC) -o $(BIN_DIRECTORY)/pagerank$(SUFFIX_COMBINER)$(SUFFIX_SINGLE_BROADCAST) $(BENCHMARKS_DIRECTORY)/pagerank.c -I$(SRC_DIRECTORY) -std=c99 $(DEFINES) $(DEFINES_COMBINER) $(DEFINES_SINGLE_BROADCAST) $(CFLAGS)

pagerank$(SUFFIX_COMBINER)$(SUFFIX_SINGLE_BROADCAST)$(SUFFIX_UNUSED_OUT_NEIGHBOURS_VALUES):
	$(CC) -o $(BIN_DIRECTORY)/pagerank$(SUFFIX_COMBINER)$(SUFFIX_SINGLE_BROADCAST)$(SUFFIX_UNUSED_OUT_NEIGHBOURS_VALUES) $(BENCHMARKS_DIRECTORY)/pagerank.c -I$(SRC_DIRECTORY) -std=c99 $(DEFINES) $(DEFINES_COMBINER) $(DEFINES_SINGLE_BROADCAST) $(DEFINES_UNUSED_OUT_NEIGHBOURS_VALUES) $(CFLAGS)

########
# SSSP #
########
all_sssp: sssp$(SUFFIX_NO_COMBINER) \
		  sssp$(SUFFIX_COMBINER)$(SUFFIX_MUTEX) \
		  sssp$(SUFFIX_COMBINER)$(SUFFIX_MUTEX)$(SUFFIX_UNUSED_IN_NEIGHBOURS) \
		  sssp$(SUFFIX_COMBINER)$(SUFFIX_MUTEX)$(SUFFIX_SPREAD) \
		  sssp$(SUFFIX_COMBINER)$(SUFFIX_MUTEX)$(SUFFIX_SPREAD)$(SUFFIX_UNUSED_IN_NEIGHBOURS) \
		  sssp$(SUFFIX_COMBINER)$(SUFFIX_SPINLOCK) \
		  sssp$(SUFFIX_COMBINER)$(SUFFIX_SPINLOCK)$(SUFFIX_UNUSED_IN_NEIGHBOURS) \
		  sssp$(SUFFIX_COMBINER)$(SUFFIX_SPINLOCK)$(SUFFIX_SPREAD) \
		  sssp$(SUFFIX_COMBINER)$(SUFFIX_SPINLOCK)$(SUFFIX_SPREAD)$(SUFFIX_UNUSED_IN_NEIGHBOURS) \
		  sssp$(SUFFIX_COMBINER)$(SUFFIX_SINGLE_BROADCAST) \
		  sssp$(SUFFIX_COMBINER)$(SUFFIX_SINGLE_BROADCAST)$(SUFFIX_UNUSED_OUT_NEIGHBOURS_VALUES) \
		  sssp$(SUFFIX_COMBINER)$(SUFFIX_SINGLE_BROADCAST)$(SUFFIX_SPREAD)

sssp$(SUFFIX_NO_COMBINER):
	$(CC) -o $(BIN_DIRECTORY)/sssp$(SUFFIX_NO_COMBINER) $(BENCHMARKS_DIRECTORY)/sssp.c -I$(SRC_DIRECTORY) -std=c99 $(DEFINES) $(CFLAGS)

sssp$(SUFFIX_COMBINER)$(SUFFIX_MUTEX):
	$(CC) -o $(BIN_DIRECTORY)/sssp$(SUFFIX_COMBINER)$(SUFFIX_MUTEX) $(BENCHMARKS_DIRECTORY)/sssp.c -I$(SRC_DIRECTORY) -std=c99 $(DEFINES) $(DEFINES_COMBINER) $(DEFINES_MUTEX) $(CFLAGS)

sssp$(SUFFIX_COMBINER)$(SUFFIX_MUTEX)$(SUFFIX_UNUSED_IN_NEIGHBOURS):
	$(CC) -o $(BIN_DIRECTORY)/sssp$(SUFFIX_COMBINER)$(SUFFIX_MUTEX)$(SUFFIX_UNUSED_IN_NEIGHBOURS) $(BENCHMARKS_DIRECTORY)/sssp.c -I$(SRC_DIRECTORY) -std=c99 $(DEFINES) $(DEFINES_COMBINER) $(DEFINES_MUTEX) $(DEFINES_UNUSED_IN_NEIGHBOURS) $(CFLAGS)

sssp$(SUFFIX_COMBINER)$(SUFFIX_MUTEX)$(SUFFIX_SPREAD):
	$(CC) -o $(BIN_DIRECTORY)/sssp$(SUFFIX_COMBINER)$(SUFFIX_MUTEX)$(SUFFIX_SPREAD) $(BENCHMARKS_DIRECTORY)/sssp.c -I$(SRC_DIRECTORY) -std=c99 $(DEFINES) $(DEFINES_COMBINER) $(DEFINES_MUTEX) $(DEFINES_SPREAD) $(CFLAGS)

sssp$(SUFFIX_COMBINER)$(SUFFIX_MUTEX)$(SUFFIX_SPREAD)$(SUFFIX_UNUSED_IN_NEIGHBOURS):
	$(CC) -o $(BIN_DIRECTORY)/sssp$(SUFFIX_COMBINER)$(SUFFIX_MUTEX)$(SUFFIX_SPREAD)$(SUFFIX_UNUSED_IN_NEIGHBOURS) $(BENCHMARKS_DIRECTORY)/sssp.c -I$(SRC_DIRECTORY) -std=c99 $(DEFINES) $(DEFINES_COMBINER) $(DEFINES_MUTEX) $(DEFINES_SPREAD) $(DEFINES_UNUSED_IN_NEIGHBOURS) $(CFLAGS)

sssp$(SUFFIX_COMBINER)$(SUFFIX_SPINLOCK):
	$(CC) -o $(BIN_DIRECTORY)/sssp$(SUFFIX_COMBINER)$(SUFFIX_SPINLOCK) $(BENCHMARKS_DIRECTORY)/sssp.c -I$(SRC_DIRECTORY) -std=gnu99 $(DEFINES) $(DEFINES_COMBINER) $(DEFINES_SPINLOCK) $(CFLAGS)

sssp$(SUFFIX_COMBINER)$(SUFFIX_SPINLOCK)$(SUFFIX_UNUSED_IN_NEIGHBOURS):
	$(CC) -o $(BIN_DIRECTORY)/sssp$(SUFFIX_COMBINER)$(SUFFIX_SPINLOCK)$(SUFFIX_UNUSED_IN_NEIGHBOURS) $(BENCHMARKS_DIRECTORY)/sssp.c -I$(SRC_DIRECTORY) -std=gnu99 $(DEFINES) $(DEFINES_COMBINER) $(DEFINES_SPINLOCK) $(DEFINES_UNUSED_IN_NEIGHBOURS) $(CFLAGS)

sssp$(SUFFIX_COMBINER)$(SUFFIX_SPINLOCK)$(SUFFIX_SPREAD):
	$(CC) -o $(BIN_DIRECTORY)/sssp$(SUFFIX_COMBINER)$(SUFFIX_SPINLOCK)$(SUFFIX_SPREAD) $(BENCHMARKS_DIRECTORY)/sssp.c -I$(SRC_DIRECTORY) -std=gnu99 $(DEFINES) $(DEFINES_COMBINER) $(DEFINES_SPINLOCK) $(DEFINES_SPREAD) $(CFLAGS)

sssp$(SUFFIX_COMBINER)$(SUFFIX_SPINLOCK)$(SUFFIX_SPREAD)$(SUFFIX_UNUSED_IN_NEIGHBOURS):
	$(CC) -o $(BIN_DIRECTORY)/sssp$(SUFFIX_COMBINER)$(SUFFIX_SPINLOCK)$(SUFFIX_SPREAD)$(SUFFIX_UNUSED_IN_NEIGHBOURS) $(BENCHMARKS_DIRECTORY)/sssp.c -I$(SRC_DIRECTORY) -std=gnu99 $(DEFINES) $(DEFINES_COMBINER) $(DEFINES_SPINLOCK) $(DEFINES_SPREAD) $(DEFINES_UNUSED_IN_NEIGHBOURS) $(CFLAGS)

sssp$(SUFFIX_COMBINER)$(SUFFIX_SINGLE_BROADCAST):
	$(CC) -o $(BIN_DIRECTORY)/sssp$(SUFFIX_COMBINER)$(SUFFIX_SINGLE_BROADCAST) $(BENCHMARKS_DIRECTORY)/sssp.c -I$(SRC_DIRECTORY) -std=c99 $(DEFINES) $(DEFINES_COMBINER) $(DEFINES_SINGLE_BROADCAST) $(CFLAGS)

sssp$(SUFFIX_COMBINER)$(SUFFIX_SINGLE_BROADCAST)$(SUFFIX_UNUSED_OUT_NEIGHBOURS_VALUES):
	$(CC) -o $(BIN_DIRECTORY)/sssp$(SUFFIX_COMBINER)$(SUFFIX_SINGLE_BROADCAST)$(SUFFIX_UNUSED_OUT_NEIGHBOURS_VALUES) $(BENCHMARKS_DIRECTORY)/sssp.c -I$(SRC_DIRECTORY) -std=c99 $(DEFINES) $(DEFINES_COMBINER) $(DEFINES_SINGLE_BROADCAST) $(DEFINES_UNUSED_OUT_NEIGHBOURS_VALUES) $(CFLAGS)

sssp$(SUFFIX_COMBINER)$(SUFFIX_SINGLE_BROADCAST)$(SUFFIX_SPREAD):
	$(CC) -o $(BIN_DIRECTORY)/sssp$(SUFFIX_COMBINER)$(SUFFIX_SINGLE_BROADCAST)$(SUFFIX_SPREAD) $(BENCHMARKS_DIRECTORY)/sssp.c -I$(SRC_DIRECTORY) -std=c99 $(DEFINES) $(DEFINES_COMBINER) $(DEFINES_SPREAD) $(DEFINES_SINGLE_BROADCAST) $(CFLAGS)

clean:
	rm -rf $(BIN_DIRECTORY)
